"""Abstract base class for all trading strategies."""

from abc import ABC, abstractmethod
from datetime import datetime, timezone
from typing import Optional

import pandas as pd

from src.models.signals import Signal, SignalDirection
from src.utils.logger import get_logger


class BaseStrategy(ABC):
    """
    Abstract base class for all XAUUSD trading strategies.

    Every concrete strategy must implement the ``generate_signal`` method,
    which takes an OHLCV DataFrame and returns a ``Signal`` instance.

    Args:
        name: Human-readable strategy name.
        symbol: Instrument symbol (default 'XAUUSD').
    """

    def __init__(self, name: str, symbol: str = "XAUUSD") -> None:
        self.name = name
        self.symbol = symbol
        self.logger = get_logger(f"strategy.{name}")
        self._last_signal: Optional[Signal] = None

    # ------------------------------------------------------------------
    # Abstract interface
    # ------------------------------------------------------------------

    @abstractmethod
    def generate_signal(self, df: pd.DataFrame) -> Signal:
        """
        Analyse market data and produce a trading signal.

        Args:
            df: OHLCV DataFrame with a DatetimeIndex.  Strategy
                implementations may expect additional pre-computed
                indicator columns (e.g. 'atr', 'volume_ma').

        Returns:
            A ``Signal`` describing the recommended trade direction.
        """

    # ------------------------------------------------------------------
    # Helpers available to all strategies
    # ------------------------------------------------------------------

    def _neutral_signal(self, reason: str = "") -> Signal:
        """Return a neutral (no-trade) signal."""
        signal = Signal(
            strategy_name=self.name,
            direction=SignalDirection.NEUTRAL,
            strength=0.0,
            timestamp=datetime.now(timezone.utc),
            symbol=self.symbol,
            metadata={"reason": reason},
        )
        self._last_signal = signal
        return signal

    def _build_signal(
        self,
        direction: SignalDirection,
        strength: float,
        entry_price: Optional[float] = None,
        stop_loss: Optional[float] = None,
        take_profit: Optional[float] = None,
        metadata: Optional[dict] = None,
    ) -> Signal:
        """
        Construct and cache a Signal with standard fields populated.

        Args:
            direction: LONG, SHORT, or NEUTRAL.
            strength: Confidence score in [-1.0, 1.0].
            entry_price: Suggested entry price.
            stop_loss: Stop-loss price.
            take_profit: Take-profit price.
            metadata: Extra information to include in the signal.

        Returns:
            Populated Signal instance.
        """
        signal = Signal(
            strategy_name=self.name,
            direction=direction,
            strength=strength,
            timestamp=datetime.now(timezone.utc),
            symbol=self.symbol,
            entry_price=entry_price,
            stop_loss=stop_loss,
            take_profit=take_profit,
            metadata=metadata or {},
        )
        self._last_signal = signal
        self.logger.info(
            "Signal: direction=%s strength=%.2f sl=%s tp=%s",
            direction.value,
            strength,
            stop_loss,
            take_profit,
        )
        return signal

    @property
    def last_signal(self) -> Optional[Signal]:
        """The most recent signal generated by this strategy."""
        return self._last_signal

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Strategy name={self.name!r} symbol={self.symbol!r}>"
