"""Data models (signals, orders, positions) for the XAUUSD Trading Bot."""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Optional


class SignalDirection(str, Enum):
    """Trade signal direction."""

    LONG = "long"
    SHORT = "short"
    NEUTRAL = "neutral"


class OrderType(str, Enum):
    """Order type."""

    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"


class OrderSide(str, Enum):
    """Order side."""

    BUY = "BUY"
    SELL = "SELL"


class OrderStatus(str, Enum):
    """Order execution status."""

    PENDING = "PENDING"
    FILLED = "FILLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


@dataclass
class Signal:
    """
    Represents a trading signal generated by a strategy.

    Attributes:
        strategy_name: Name of the strategy that generated the signal.
        direction: Trade direction (LONG, SHORT, or NEUTRAL).
        strength: Signal confidence score in the range [-1.0, 1.0].
        timestamp: UTC time at which the signal was generated.
        symbol: Instrument symbol (e.g. 'XAUUSD').
        entry_price: Suggested entry price (None for market order).
        stop_loss: Suggested stop-loss price.
        take_profit: Suggested take-profit price.
        metadata: Arbitrary additional information from the strategy.
    """

    strategy_name: str
    direction: SignalDirection
    strength: float                   # [-1.0, 1.0]
    timestamp: datetime
    symbol: str = "XAUUSD"
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    metadata: dict = field(default_factory=dict)

    def to_vote(self) -> int:
        """Convert the signal direction to a confluence vote (+1, -1, or 0)."""
        if self.direction == SignalDirection.LONG:
            return 1
        if self.direction == SignalDirection.SHORT:
            return -1
        return 0


@dataclass
class Order:
    """
    Represents a trading order to be submitted to the broker.

    Attributes:
        symbol: Instrument symbol.
        side: BUY or SELL.
        order_type: Order type (MARKET, LIMIT, STOP, STOP_LIMIT).
        quantity: Number of units to trade.
        limit_price: Limit price (required for LIMIT and STOP_LIMIT orders).
        stop_price: Stop price (required for STOP and STOP_LIMIT orders).
        take_profit: Attached take-profit price.
        stop_loss: Attached stop-loss price.
        strategy_name: Strategy that generated this order.
        created_at: UTC time when the order was created.
        status: Current order status.
        order_id: Broker-assigned order identifier.
    """

    symbol: str
    side: OrderSide
    order_type: OrderType
    quantity: float
    limit_price: Optional[float] = None
    stop_price: Optional[float] = None
    take_profit: Optional[float] = None
    stop_loss: Optional[float] = None
    strategy_name: str = ""
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    status: OrderStatus = OrderStatus.PENDING
    order_id: Optional[str] = None


@dataclass
class Position:
    """
    Represents an open position.

    Attributes:
        symbol: Instrument symbol.
        side: Direction of the position (BUY = long, SELL = short).
        quantity: Current open quantity.
        entry_price: Average fill price of the entry order(s).
        current_price: Most recent market price.
        stop_loss: Active stop-loss level.
        take_profit: Active take-profit level.
        strategy_name: Strategy that opened the position.
        opened_at: UTC time when the position was opened.
        unrealised_pnl: Unrealised P&L at the current price.
    """

    symbol: str
    side: OrderSide
    quantity: float
    entry_price: float
    current_price: float = 0.0
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    strategy_name: str = ""
    opened_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    unrealised_pnl: float = 0.0

    def update_pnl(self) -> None:
        """Recalculate unrealised P&L based on the current price."""
        if self.side == OrderSide.BUY:
            self.unrealised_pnl = (self.current_price - self.entry_price) * self.quantity
        else:
            self.unrealised_pnl = (self.entry_price - self.current_price) * self.quantity


@dataclass
class TradeResult:
    """
    Represents the outcome of a completed (closed) trade.

    Attributes:
        symbol: Instrument symbol.
        strategy_name: Strategy that generated the trade.
        side: Original trade direction (BUY = long, SELL = short).
        quantity: Number of units traded.
        entry_price: Fill price at entry.
        exit_price: Fill price at exit.
        pnl: Realised profit / loss.
        opened_at: UTC time the trade was opened.
        closed_at: UTC time the trade was closed.
        exit_reason: Short description of why the trade was closed.
    """

    symbol: str
    strategy_name: str
    side: OrderSide
    quantity: float
    entry_price: float
    exit_price: float
    pnl: float
    opened_at: datetime
    closed_at: datetime
    exit_reason: str = ""
